# Generated by Django 2.2.1 on 2019-05-14 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('range', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('q', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('searchKey', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twtscopy.City')),
            ],
        ),
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twtscopy.Tweets')),
            ],
        ),
    ]
